name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Enables pushing using GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: python src/models/train.py
     
      - name: Check GITHUB_TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          #git config --global user.name "github-actions"
          #git config --global user.email "kamal480@users.noreply.github.com"
          git add src/models/classification_model.pkl
          git commit -m "Add trained model file" || echo "No changes to commit"
          git push https://github.com/kamal480/Classification.git
